In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np

### Reading The CSV File

In [3]:
insu=pd.read_csv('insurance.csv')

In [4]:
insu.head(10)

member_name                     email  gender   location    employer  \
0       Chipi        ajimmison0@sun.com  female     Kwekwe        Vipe   
1       Femba     rsoonhouse1@google.it  female  Marondera        Mudo   
2        Geta  bchecchetelli2@house.gov  female     Rusape      Skaboo   
3    Tichaona          mgarman3@psu.edu  female     Rusape   Babbleset   
4       Chisa     ccough4@biglobe.ne.jp  female   Bulawayo    Flipopia   
5       Gweta       mhylden5@sfgate.com  female     Kwekwe  Brainverse   
6       Konde          mlent6@patch.com    male     Rusape    Photobug   
7       Gweta       mpicford7@apple.com    male     Nyanga      Avamba   
8     Sibanda         thappert8@psu.edu    male     Harare    Feedspan   
9       Evans   erainbow9@pinterest.com    male   Masvingo    Fiveclub   

  relationship patient_name  patient_suffix patient_dob  \
0  Grandfather      Mabhena             789  09-11-1997   
1      Husband      Sithole             860   1/14/1992   
2       Mother        Chipi             374  07-03-1999   
3       Father       Jembwa             729   7/31/1978   
4       Father         Foto             716  12/28/1992   
5     Daughter        Evans             160  06-12-1974   
6       Nepfew        Chiri             626  10/24/2001   
7      Brother  Chisa Chisi             318   1/17/1973   
8        Niece         Geta             715  06-05-2002   
9       Mother      Sithole             887   4/14/1984   

                   cause  Fee_Charged  membership_period  number_of_claims  \
0                  Other         3798               1541                 2   
1                  Other        48905               8269                 4   
2  Road Traffic Accident        39963               6223                 2   
3  Road Traffic Accident        34948               8832                 6   
4       Accident At Work        46984               8804                 1   
5                  Other        37298               2445                 2   
6  Road Traffic Accident        33981               3715                 4   
7                  Other         5071                541                 1   
8                  Other        22943               8690                 5   
9       Accident At Work        27104               6680                 2   

   number_of_dependants  label  
0                     4      0  
1                     3      0  
2                     2      0  
3                     3      0  
4                     2      1  
5                     4      0  
6                     1      0  
7                     3      0  
8                     2      1  
9                     3      0

### Know the size of the data

In [5]:
insu.shape # To see matrix structure.

(11242, 15)

### Know what are the columns are there in the csv file?

In [6]:
insu.columns

Index(['member_name', 'email', 'gender', 'location', 'employer',
       'relationship', 'patient_name', 'patient_suffix', 'patient_dob',
       'cause', 'Fee_Charged', 'membership_period', 'number_of_claims',
       'number_of_dependants', 'label'],
      dtype='object')

### Information regarding csv File

In [7]:
insu.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11242 entries, 0 to 11241
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   member_name           11242 non-null  object
 1   email                 11242 non-null  object
 2   gender                11242 non-null  object
 3   location              11242 non-null  object
 4   employer              11242 non-null  object
 5   relationship          11242 non-null  object
 6   patient_name          11242 non-null  object
 7   patient_suffix        11242 non-null  int64 
 8   patient_dob           11242 non-null  object
 9   cause                 11242 non-null  object
 10  Fee_Charged           11242 non-null  int64 
 11  membership_period     11242 non-null  int64 
 12  number_of_claims      11242 non-null  int64 
 13  number_of_dependants  11242 non-null  int64 
 14  label                 11242 non-null  int64 
dtypes: int64(6), object(9)
memory usage:

### To check is there any null value?


In [8]:
insu.isnull().sum() # if no null value are there No need to do dropna or fillna

member_name             0
email                   0
gender                  0
location                0
employer                0
relationship            0
patient_name            0
patient_suffix          0
patient_dob             0
cause                   0
Fee_Charged             0
membership_period       0
number_of_claims        0
number_of_dependants    0
label                   0
dtype: int64

### To check any duplication of data

In [9]:
insu.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...  
11237     True
11238     True
11239     True
11240     True
11241     True
Length: 11242, dtype: bool

### To Check How many duplicate data are there

In [10]:
insu.duplicated().sum()

4242

### To remove duplicate Entries

In [11]:
insu = insu.drop_duplicates()

### Check data size after deleting duplicates

In [12]:
insu.shape

(7000, 15)

### Information about csv file after removing duplicates

In [13]:
insu.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7000 entries, 0 to 6999
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   member_name           7000 non-null   object
 1   email                 7000 non-null   object
 2   gender                7000 non-null   object
 3   location              7000 non-null   object
 4   employer              7000 non-null   object
 5   relationship          7000 non-null   object
 6   patient_name          7000 non-null   object
 7   patient_suffix        7000 non-null   int64 
 8   patient_dob           7000 non-null   object
 9   cause                 7000 non-null   object
 10  Fee_Charged           7000 non-null   int64 
 11  membership_period     7000 non-null   int64 
 12  number_of_claims      7000 non-null   int64 
 13  number_of_dependants  7000 non-null   int64 
 14  label                 7000 non-null   int64 
dtypes: int64(6), object(9)
memory usage: 8

### Let we check the unique data of Each columns.

In [14]:
insu['gender'].unique()

array(['female', 'male'], dtype=object)

In [15]:
insu['cause'].unique()

array(['Other', 'Road Traffic Accident', 'Accident At Work',
       'Accident At Home'], dtype=object)

In [16]:
insu['Fee_Charged'].unique()

array([ 3798, 48905, 39963, ..., 32895, 19082, 29020], dtype=int64)

In [17]:
insu['membership_period'].unique()

array([1541, 8269, 6223, ..., 7887, 6478, 8293], dtype=int64)

In [18]:
insu['number_of_claims'].unique()

array([2, 4, 6, 1, 5, 3], dtype=int64)

In [19]:
insu['number_of_dependants'].unique()

array([4, 3, 2, 1], dtype=int64)

In [20]:
insu['label'].unique()

array([0, 1], dtype=int64)

## Replacing cause and gender data with values :

### Changing the objects to numericals.

In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

var = ['cause','gender']

for i in var:
    insu[i] = le.fit_transform(insu[i]).astype(int)

In [22]:
insu

member_name                     email  gender   location   employer  \
0           Chipi        ajimmison0@sun.com       0     Kwekwe       Vipe   
1           Femba     rsoonhouse1@google.it       0  Marondera       Mudo   
2            Geta  bchecchetelli2@house.gov       0     Rusape     Skaboo   
3        Tichaona          mgarman3@psu.edu       0     Rusape  Babbleset   
4           Chisa     ccough4@biglobe.ne.jp       0   Bulawayo   Flipopia   
...           ...                       ...     ...        ...        ...   
6995        Mirwa    gcobbern@microsoft.com       1     Kwekwe     Trudeo   
6996  Chisa Chisi   ebrasierro@sakura.ne.jp       1      Gweru    Jetwire   
6997        Evans     ybuckyrp@slashdot.org       1     Rusape  Realpoint   
6998        Femba   raskawrq@washington.edu       0      Gweru     Eimbee   
6999      Sithole     wlantrr@quantcast.com       1      Gweru    Camimbo   

     relationship patient_name  patient_suffix patient_dob  cause  \
0     Grandfather      Mabhena             789  09-11-1997      2   
1         Husband      Sithole             860   1/14/1992      2   
2          Mother        Chipi             374  07-03-1999      3   
3          Father       Jembwa             729   7/31/1978      3   
4          Father         Foto             716  12/28/1992      1   
...           ...          ...             ...         ...    ...   
6995  Grandmother      Mabhena             595  11/30/1984      2   
6996      Husband         Bima             158  08-06-1986      0   
6997     Daughter        Dihwa             743   2/13/1980      0   
6998      Brother     Peterson             472  12/28/2001      2   
6999       Mother      Sibanda             625   3/21/2003      2   

      Fee_Charged  membership_period  number_of_claims  number_of_dependants  \
0            3798               1541                 2                     4   
1           48905               8269                 4                     3   
2           39963               6223                 2                     2   
3           34948               8832                 6                     3   
4           46984               8804                 1                     2   
...           ...                ...               ...                   ...   
6995        25308               6478                 4                     3   
6996        32895                438                 1                     1   
6997        19082               8134                 3                     1   
6998        31717               8293                 4                     3   
6999        29020               3686                 3                     4   

      label  
0         0  
1         0  
2         0  
3         0  
4         1  
...     ...  
6995      0  
6996      0  
6997      0  
6998      1  
6999      0  

[7000 rows x 15 columns]

### Again Check the unique values

In [23]:
features=['gender','cause','Fee_Charged','membership_period','number_of_claims','number_of_dependants']
target=['label']
for i in features:
    z=insu[i].unique()
    print(z)

[0 1]
[2 3 1 0]
[ 3798 48905 39963 ... 32895 19082 29020]
[1541 8269 6223 ... 7887 6478 8293]
[2 4 6 1 5 3]
[4 3 2 1]


In [24]:
insu.corr()

gender  patient_suffix     cause  Fee_Charged  \
gender                1.000000       -0.004818 -0.003877     0.016833   
patient_suffix       -0.004818        1.000000 -0.008980    -0.018051   
cause                -0.003877       -0.008980  1.000000    -0.003148   
Fee_Charged           0.016833       -0.018051 -0.003148     1.000000   
membership_period     0.008275       -0.005959 -0.012087     0.004625   
number_of_claims     -0.010652        0.002866  0.017807    -0.014635   
number_of_dependants -0.005804       -0.008423 -0.003160    -0.010560   
label                 0.000684       -0.001051  0.002203     0.011846   

                      membership_period  number_of_claims  \
gender                         0.008275         -0.010652   
patient_suffix                -0.005959          0.002866   
cause                         -0.012087          0.017807   
Fee_Charged                    0.004625         -0.014635   
membership_period              1.000000         -0.001084   
number_of_claims              -0.001084          1.000000   
number_of_dependants          -0.019292         -0.020563   
label                         -0.010831         -0.005216   

                      number_of_dependants     label  
gender                           -0.005804  0.000684  
patient_suffix                   -0.008423 -0.001051  
cause                            -0.003160  0.002203  
Fee_Charged                      -0.010560  0.011846  
membership_period                -0.019292 -0.010831  
number_of_claims                 -0.020563 -0.005216  
number_of_dependants              1.000000 -0.015572  
label                            -0.015572  1.000000